# Database Configuration
db.url=jdbc:oracle:thin:@//localhost:1521/DB_PDB_NAME
db.username=DB_USER
db.password=DB_PASSWORD

# Connection Pool
db.pool.initial=2
db.pool.min=2
db.pool.max=5

# Monitoring
monitoring.checkIntervalSeconds = 5

# Liquibase Configuration
liquibase.changeLog=db/changelog/db.changelog-master.yaml
liquibase.contexts=default
liquibase.dropFirst=false

# Application
app.name=backend
app.version=1.0.0
app.ping.interval.ms=5000