/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.victormartin.rac;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test
    void basicTest() {
        Main classUnderTest = new Main();
        assertNotNull(classUnderTest, "Main should instantiate");
    }
}
