/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.victormartin.rac;

import dev.victormartin.rac.config.DatabaseConfig;
import dev.victormartin.rac.model.Ping;
import dev.victormartin.rac.repository.PingRepository;
import dev.victormartin.rac.service.DatabaseMonitoringService;
import dev.victormartin.rac.service.LiquibaseMigrationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.time.Instant;
import java.util.Properties;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class Main {
    private static final Logger logger = LoggerFactory.getLogger(Main.class);
    private static volatile boolean running = true;
    private static ScheduledExecutorService scheduler;

    public static void main(String[] args) {
        run();
    }

    public static void run() {
        try {
            Properties config = loadConfiguration();
            DatabaseConfig dbConfig = new DatabaseConfig(config);

            // Add shutdown hook for graceful cleanup
            Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                logger.info("Shutting down application...");
                running = false;
                if (scheduler != null && !scheduler.isShutdown()) {
                    scheduler.shutdown();
                    try {
                        if (!scheduler.awaitTermination(5, TimeUnit.SECONDS)) {
                            scheduler.shutdownNow();
                        }
                    } catch (InterruptedException e) {
                        scheduler.shutdownNow();
                        Thread.currentThread().interrupt();
                    }
                }
                dbConfig.close();
                logger.info("Application shutdown complete");
            }));

            // Run Liquibase migrations
            LiquibaseMigrationService migrationService = new LiquibaseMigrationService(dbConfig.getDataSource(),
                    config);
            migrationService.runMigrations();

            // Run Database Monitoring for Prometheus
            DatabaseMonitoringService dbMonitoringService = new DatabaseMonitoringService(dbConfig, config);
            dbMonitoringService.start();

            PingRepository pingRepository = new PingRepository(dbConfig.getDataSource());

            // Health check
            if (!dbConfig.isHealthy()) {
                throw new RuntimeException("Database connection pool is not healthy");
            }

            logger.info("Database connection pool is healthy");

            // Get ping interval from configuration
            long pingIntervalMs = Long.parseLong(config.getProperty("app.ping.interval.ms", "5000"));
            logger.info("Starting ping scheduler with interval: {}ms", pingIntervalMs);

            // Initialize scheduler
            scheduler = Executors.newScheduledThreadPool(1);

            // Schedule ping creation
            scheduler.scheduleAtFixedRate(() -> {
                try {
                    String origin = config.getProperty("app.name", "backend");
                    Ping ping = new Ping(origin, Instant.now());
                    Ping savedPing = pingRepository.save(ping);
                    logger.info("Created ping with id: {}, client timestamp: {}, server timestamp: {}",
                            savedPing.id(), savedPing.clientTimestamp(), savedPing.serverTimestamp());
                } catch (Exception e) {
                    logger.error("Failed to create ping", e);
                }
            }, 0, pingIntervalMs, TimeUnit.MILLISECONDS);

            logger.info("Backend started successfully and ping scheduler is running");

            // Keep the application running
            while (running) {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
            }

        } catch (Exception e) {
            logger.error("Backend startup failed", e);
            System.exit(1);
        }
    }

    private static Properties loadConfiguration() throws IOException {
        Properties props = new Properties();
        try (InputStream is = Main.class.getResourceAsStream("/application.properties")) {
            if (is == null) {
                throw new IOException("application.properties not found");
            }
            props.load(is);
        }

        // Load local overrides
        try (InputStream localIs = Main.class.getResourceAsStream("/application-local.properties")) {
            if (localIs != null) {
                Properties localProps = new Properties();
                localProps.load(localIs);
                props.putAll(localProps); // Local properties override base properties
            }
        }

        // Override with system properties
        props.putAll(System.getProperties());

        return props;
    }

}